// Bundled patch notes — shown in the "What's new" modal after an update.
// Add an entry here with every release so users always see real notes.
export const RELEASE_NOTES = {
  '0.25.0': `• Proactive coach brief on the Dashboard — an at-a-glance process review that refreshes as your trades change, with an optional AI touch (toggle it in Settings)\n• Share report — export a clean PNG snapshot of your stats to share, with a date range and account label`,
  '0.24.2': `• Cosmetic polish — gradient-filled equity curve, frosted-glass floating widgets and pop-ups, hover lift on cards, aligned tabular numbers, and green/red accents on trade-history rows`,
  '0.24.1': `• New prop firm achievements — "First Payout" unlocks on your first one, and a "Payday" medal climbs an 8-tier ladder (Wood → Steel → Bronze → Silver → Gold → Platinum → Diamond → Legendary) as your payout count grows`,
  '0.24.0': `• Tag each trade as Live or a specific prop account right in the journal\n• Dashboard now has a Live / Prop / All toggle so your prop and live P&L stay separate (letter grade still combines both)\n• Prop accounts now count only the trades you tag to them by default — your live trades no longer leak in\n• Each account card shows two bars: progress toward target AND drawdown cushion\n• Track prop firm payouts — per account and an all-time log`,
  '0.23.2': `• The floating Trade Mode news widget now always shows while you're live — even when there's no upcoming news (so you know you're clear)`,
  '0.23.1': `• Economic calendar now floats in the corner while Trade Mode is live, so upcoming news stays in view — imminent high-impact events glow red, and it collapses to a pill when you want it out of the way`,
  '0.23.0': `• Simple journal mode — toggle it on to hide the price/risk fields and log a trade in under a minute (keeps screenshots)\n• No-trade day tracker — log days you sat out or missed, with a reason and mood, without touching your P&L\n• Add your own custom emotions and setups with a + button\n• Setup is now a clean dropdown instead of free-text`,
  '0.22.4': `• Update banner now clearly says the new version downloaded in the background — just click Restart to apply, no browser or download page`,
  '0.22.3': `• Windows updates are fully automatic again — the app downloads in the background and shows a "Restart now" button to update instantly\n• Added Performance heat map and Playbook to the website`,
  '0.22.2': `• Fixed releases being published as drafts — landing page download and in-app update now work correctly`,
  '0.22.1': `• Update check interval reduced to 10s for testing`,
  '0.22.0': `• Update banner now appears on Windows when a new version is available — click to download the latest installer directly`,
  '0.21.8': `• Fixed CI workflow (removed release-notes job that was failing)`,
  '0.21.7': `• Restored original update flow: app silently downloads update and shows a bottom-left 'Restart now' banner`,
  '0.21.6': `• Fixed CI release-notes generation`,
  '0.21.4': `• Update notifications now work on all platforms — a banner appears when a new version is out with a direct download link\n• Fixed update delivery that was silently broken for Windows users`,
  '0.21.3': `• Update flow is now user-triggered: banner shows when an update is available, click "Update now" to download, then "Restart now" to apply`,
  '0.21.2': `• Heat map advisory now shows best hour and best day as separate chips`,
  '0.21.1': `• Heat map advisory fixed to correctly highlight the single best performing time slot`,
  '0.21.0': `• Performance heat map on the Dashboard — win rate by hour × day with a fire color scale and advisory\n• Playbook tab — document your setups with entry criteria, invalidation, and targets; trades auto-link by setup name`,
  '0.20.3': `• Security: settings write-side key allowlist\n• Security: image upload MIME allowlist blocks SVGs\n• Performance: trade list query rewritten to use a single JOIN\n• Reliability: settings cache invalidated on every write\n• openExternal restricted to http/https URLs only\n• Stream listener cleanup on component unmount\n• getImage returns null on file error instead of crashing\n• Backup errors now logged instead of swallowed`,
}
